### ISSUE TITLE
Link flair not appearing in subvoat.

### ISSUE THREAD

**Issue by Phoenixwolf** [Phoenixwolf/simplegoats#14]
.flair-Music {
	color: white;
	background: blue;
	border-radius: 4px;
	display: inline-block;
	font-family: inherit;
	font-size: 10px;
	letter-spacing: 1px;
	line-height: 11px;
	margin-right: 3px;
	max-width: 60px;
	min-width: 48px;
	overflow: hidden;
	padding: 2px;
	text-align: center;
	white-space: nowrap;
	text-transform: lowercase;
}

**Comment by Phoenixwolf** [comment]
Fixed by adding:
```CSS
.flair{
display:inline-block;
vertical-align: top;
}

#linkflair{
display:none;
}
```
